steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$BRANCH_NAME', '.']
- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/$PROJECT_ID/$BRANCH_NAME']
- name: gcr.io/cloud-builders/gcloud
  args: ['app', 'deploy', '-v', 'local','--image-url=gcr.io/$PROJECT_ID/$BRANCH_NAME']